services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: shoploc123
      POSTGRES_DB: shoploc_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: