name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Backend
        run: mvn clean install -f shoplocBackend/pom.xml
      - name: Deploy Backend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Deploying Backend to Heroku..."
          heroku plugins:install @heroku-cli/plugin-manifest
          heroku plugins:install @heroku-cli/plugin-manifest
          heroku authorizations:create --description "GitHub Actions" | grep "token" | cut -d '"' -f 4 > apikey.txt
          heroku config:set HEROKU_API_KEY=$(cat apikey.txt)
          heroku deploy --app shoploc --app-dir shoplocBackend
